# Generated by Django 2.2 on 2022-12-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://ticketlinkz.com/wp-content/uploads/2014/12/EVENT-PLACEHOLDER.jpg', max_length=500),
        ),
    ]
