# Generated by Django 2.2 on 2022-12-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://cdn1.vectorstock.com/i/1000x1000/33/30/default-placeholder-avatar-set-profile-vector-21473330.jpg', max_length=500),
        ),
    ]
